# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import getRandomMovie


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 339)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color : #012940;")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Sweden))
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.posterImage = QtWidgets.QLabel(self.centralwidget)
        self.posterImage.setGeometry(QtCore.QRect(20, 70, 180, 240))
        self.posterImage.setScaledContents(True)
        self.posterImage.setObjectName("posterImage")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 70, 760, 40))
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setStyleSheet('''    color : white;
                                        font: bold 24pt "Avenir"; ''')
        self.title.setObjectName("title")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 160, 50, 30))
        self.label_3.setStyleSheet('''  color : white;
                                        font: bold 18pt "Avenir"; ''')
        self.label_3.setObjectName("label_3")

        self.crewList = QtWidgets.QLabel(self.centralwidget)
        self.crewList.setGeometry(QtCore.QRect(280, 160, 700, 30))
        self.crewList.setStyleSheet(''' color : white;
                                        font: 18pt "Avenir";  ''')
        self.crewList.setObjectName("crewList")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 50))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color : #011826;")
        self.widget.setObjectName("widget")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 240, 30))
        self.label.setStyleSheet('''    font: 24pt "Raleway";
                                        color: white;   ''')
        self.label.setObjectName("label")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(690, 0, 290, 50))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(''' QPushButton {
                                                background-color: #A60D70;
                                                color: white;
                                                font: bold 16pt "Avenir";
                                                border-radius: 15px;
                                                margin-right: 5px;
                                            }

                                            QPushButton:hover {
                                                background-color: #960c66;
                                            }

                                            QPushButton:pressed {
                                                background-color: #87095b;
                                            }   ''')
        self.pushButton_2.setObjectName("pushButton_2")

        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet('''   QPushButton {
                                                background-color: #A60D70;
                                                color: white;
                                                font: bold 16pt "Avenir";
                                                border-radius: 15px;
                                                margin-right: 5px;
                                            }

                                            QPushButton:hover {
                                                background-color: #960c66;
                                            }

                                            QPushButton:pressed {
                                                background-color: #87095b;
                                            }   ''')
        self.pushButton.setObjectName("pushButton")

        self.horizontalLayout_3.addWidget(self.pushButton)

        self.trailerLink = QtWidgets.QLabel(self.centralwidget)
        self.trailerLink.setGeometry(QtCore.QRect(220, 200, 320, 30))
        self.trailerLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trailerLink.setStyleSheet('''  QLabel {
                                                color : #04C4D9;
                                                font: 18pt "Avenir";
                                            }

                                            QLabel:hover {
                                                font: 20pt "Avenir";
                                            }   ''')
        self.trailerLink.setObjectName("trailerLink")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 250, 760, 60))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.addToSeen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addToSeen.setMinimumSize(QtCore.QSize(0, 50))
        self.addToSeen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addToSeen.setStyleSheet(''' QPushButton {
                                                    background-color: #049DBF;
                                                    color: white;
                                                    font: bold 18pt "Avenir";
                                                    border-radius: 25px;
                                                    margin-right: 5px;
                                                }

                                                QPushButton:hover {
                                                    background-color: #058ba8;
                                                }

                                                QPushButton:pressed {
                                                    background-color: #025373;
                                                }   ''')
        self.addToSeen.setObjectName("addToSeen")
        self.horizontalLayout_2.addWidget(self.addToSeen)

        self.addToWatchlist = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addToWatchlist.setMinimumSize(QtCore.QSize(0, 50))
        self.addToWatchlist.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addToWatchlist.setStyleSheet(''' QPushButton {
                                                background-color: #049DBF;
                                                color: white;
                                                font: bold 18pt "Avenir";
                                                border-radius: 25px;
                                                margin-right: 5px;
                                                margin-left: 5px
                                            }

                                            QPushButton:hover {
                                                background-color: #058ba8;
                                            }

                                            QPushButton:pressed {
                                                background-color: #025373;
                                            }   ''')
        self.addToWatchlist.setObjectName("addToWatchlist")
        self.horizontalLayout_2.addWidget(self.addToWatchlist)

        self.newSuggestionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.newSuggestionButton.setMinimumSize(QtCore.QSize(0, 50))
        self.newSuggestionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newSuggestionButton.setStyleSheet(''' QPushButton {
                                                background-color: #049DBF;
                                                color: white;
                                                font: bold 18pt "Avenir";
                                                border-radius: 25px;
                                                margin-left: 5px
                                            }

                                            QPushButton:hover {
                                                background-color: #058ba8;
                                            }

                                            QPushButton:pressed {
                                                background-color: #025373;
                                            }   ''')
        self.newSuggestionButton.setObjectName("newSuggestionButton")
        self.newSuggestionButton.clicked.connect(self.newSuggestion)
        self.horizontalLayout_2.addWidget(self.newSuggestionButton)

        self.ratingLabel = QtWidgets.QLabel(self.centralwidget)
        self.ratingLabel.setGeometry(QtCore.QRect(220, 120, 110, 30))
        self.ratingLabel.setStyleSheet('''  color : white;
                                        font: bold 18pt "Avenir";    ''')
        self.ratingLabel.setObjectName("ratingLabel")

        self.imdbRating = QtWidgets.QLabel(self.centralwidget)
        self.imdbRating.setGeometry(QtCore.QRect(340, 120, 450, 30))
        self.imdbRating.setStyleSheet('''   color : white;
                                            font: 18pt "Avenir";  ''')
        self.imdbRating.setObjectName("imdbRating")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.newSuggestion()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("MoviePicker")
        self.label_3.setText("Crew: ")
        self.label.setText("MoviePicker")
        self.pushButton_2.setText("Seen")
        self.pushButton.setText('Watchlist')
        self.trailerLink.setText("Watch trailer (opens in YouTube)")
        self.addToSeen.setText("Already seen")
        self.addToWatchlist.setText("Add to watchlist")
        self.newSuggestionButton.setText("New suggestion")
        self.ratingLabel.setText("IMDb-rating: ")

    def newSuggestion(self):
        movie = getRandomMovie()

        try:
            self.title.setText(movie['fullTitle'])

            image_url = movie['image']
            image = QtGui.QPixmap()
            image.loadFromData(requests.get(image_url).content)
            self.posterImage.setPixmap(image)

            self.imdbRating.setText(movie['imDbRating'])

            self.crewList.setText(movie['crew'])
        except TypeError:
            print("TypeError")
            self.newSuggestion()


if __name__ == "__main__":
    import sys
    import requests
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
