# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(750, 339)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color : #012940;")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Sweden))
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.posterImage = QtWidgets.QLabel(self.centralwidget)
        self.posterImage.setGeometry(QtCore.QRect(20, 70, 181, 241))
        image_url = "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg"
        image = QtGui.QPixmap()
        image.loadFromData(requests.get(image_url).content)
        self.posterImage.setPixmap(image)
        self.posterImage.setScaledContents(True)
        self.posterImage.setObjectName("posterImage")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 70, 511, 40))
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setStyleSheet("color : white;\n"
"font: bold 24pt \"Avenir\";")
        self.title.setObjectName("title")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 160, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : white;\n"
"font: bold 18pt \"Avenir\";")
        self.label_3.setObjectName("label_3")
        self.crewList = QtWidgets.QLabel(self.centralwidget)
        self.crewList.setGeometry(QtCore.QRect(280, 160, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.crewList.setFont(font)
        self.crewList.setStyleSheet("color : white;\n"
"font: 18pt \"Avenir\";")
        self.crewList.setObjectName("crewList")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 751, 51))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color : #011826;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 241, 30))
        self.label.setStyleSheet("font: 24pt \"Raleway\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 0, 291, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #A60D70;\n"
"    color: white;\n"
"    font: bold 16pt \"Avenir\";\n"
"    border-radius: 15px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #960c66;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #87095b;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #A60D70;\n"
"    color: white;\n"
"    font: bold 16pt \"Avenir\";\n"
"    border-radius: 15px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #960c66;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #87095b;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.trailerLink = QtWidgets.QLabel(self.centralwidget)
        self.trailerLink.setGeometry(QtCore.QRect(220, 200, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trailerLink.setFont(font)
        self.trailerLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trailerLink.setStyleSheet("QLabel {\n"
"    color : #04C4D9;\n"
"    font: 18pt \"Avenir\";\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 20pt \"Avenir\";\n"
"}")
        self.trailerLink.setObjectName("trailerLink")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 250, 511, 62))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addToSeen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addToSeen.setMinimumSize(QtCore.QSize(0, 50))
        self.addToSeen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addToSeen.setStyleSheet("QPushButton {\n"
"    background-color: #049DBF;\n"
"    color: white;\n"
"    font: bold 18pt \"Avenir\";\n"
"    border-radius: 25px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #058ba8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #025373;\n"
"}")
        self.addToSeen.setObjectName("addToSeen")
        self.horizontalLayout_2.addWidget(self.addToSeen)
        self.addToWatchlist = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addToWatchlist.setMinimumSize(QtCore.QSize(0, 50))
        self.addToWatchlist.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addToWatchlist.setStyleSheet("QPushButton {\n"
"    background-color: #049DBF;\n"
"    color: white;\n"
"    font: bold 18pt \"Avenir\";\n"
"    border-radius: 25px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #058ba8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #025373;\n"
"}")
        self.addToWatchlist.setObjectName("addToWatchlist")
        self.horizontalLayout_2.addWidget(self.addToWatchlist)
        self.newSuggestion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.newSuggestion.setMinimumSize(QtCore.QSize(0, 50))
        self.newSuggestion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newSuggestion.setStyleSheet("QPushButton {\n"
"    background-color: #049DBF;\n"
"    color: white;\n"
"    font: bold 18pt \"Avenir\";\n"
"    border-radius: 25px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #058ba8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #025373;\n"
"}")
        self.newSuggestion.setObjectName("newSuggestion")
        self.horizontalLayout_2.addWidget(self.newSuggestion)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 120, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : white;\n"
"font: bold 18pt \"Avenir\";")
        self.label_4.setObjectName("label_4")
        self.crewList_2 = QtWidgets.QLabel(self.centralwidget)
        self.crewList_2.setGeometry(QtCore.QRect(340, 120, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.crewList_2.setFont(font)
        self.crewList_2.setStyleSheet("color : white;\n"
"font: 18pt \"Avenir\";")
        self.crewList_2.setObjectName("crewList_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "It\'s a Wonderful Life (1946)"))
        self.label_3.setText(_translate("MainWindow", "Crew:"))
        self.crewList.setText(_translate("MainWindow", "<html><head/><body><p>Frank Capra (dir.), James Stewart, Donna Ree</p></body></html>"))
        self.label.setText(_translate("MainWindow", "MoviePicker"))
        self.pushButton_2.setText(_translate("MainWindow", "Seen"))
        self.pushButton.setText(_translate("MainWindow", "Watchlist"))
        self.trailerLink.setText(_translate("MainWindow", "<html><head/><body><p>Watch trailer (opens in YouTube)</p></body></html>"))
        self.addToSeen.setText(_translate("MainWindow", "Already seen"))
        self.addToWatchlist.setText(_translate("MainWindow", "Add to watchlist"))
        self.newSuggestion.setText(_translate("MainWindow", "New suggestion"))
        self.label_4.setText(_translate("MainWindow", "IMDb-rating: "))
        self.crewList_2.setText(_translate("MainWindow", "<html><head/><body><p>8.6</p></body></html>"))


if __name__ == "__main__":
    import sys
    import requests
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
